### ISSUE TITLE
I maked translate it russian

### ISSUE THREAD

**Issue by vanja-san** [Snipaste/translations#2]
Please download to - https://github.com/vanja-san/Russian-translation-for-Snipaste

**Comment by septs** [comment]
Please "New Pull request"

CC @liulex

**Comment by liulex** [comment]
@vanja-san Thank you very much for your translation! It has been added into this repo (with some mismatched punctuations and extra spaces fixed) and will appear in the next release of Snipaste.

If you want to make further updates to the translation, feel free to make a pull request. 😄

**Comment by liulex** [comment]
@vanja-san A few new strings have been added. Please update the translation file and make a pull request when you have time. 😄
