### ISSUE TITLE
Did the translations move inside Weblate?

### ISSUE THREAD

**Issue by Stephan-P** [Snipaste/translations#57]
I just received an e-mail from Weblate pointing to a different location within Weblate.
Did we move?

Another question relates to the Dutch translation. Nederlands (nl_NL) is fully translated, but in the new Weblate environment there's also a brand new and fully untranslated branch Nederlands (without nl_NL). I'm pretty sure that we can do without this one.

**Comment by KazamaSion** [comment]
The email you received is referring to the status of the whole translation project, including all languages. This is why it seems like "not fully translated" to you. In fact, Dutch (nl_NL) is fully translated now.   
![](https://translations.snipaste.com/widgets/snipaste/nl_NL/snipaste/287x66-grey.png)  
The website did not get moved.   

For your second question, may the maintainer know the necessity of launching a new language branch (Dutch [nl]) while there is an existing similar one(Dutch [nl_nL]) currently? What's the difference between Dutch (nl_NL) and Dutch (nl)?

P.S. FYI, the remaining not-yet-launched translation branches are:
Dutch (nl)
Dutch (Middle) (dum)

**Comment by Stephan-P** [comment]
Genetic Dutch (nl) and Dutch (nl_NL) (the official dialect) are the same.
If one would want, Dutch (nl_BE) the Belgian (Flemmish) dialect could be made seperate, but other than that there are no dialect defined.
No need for Dutch (nl) while Dutch (NL_NL) is already in place.

**Comment by KazamaSion** [comment]
The language name "Dutch (Belgium)" is revised from "Finnish" now according to the official issue (https://github.com/WeblateOrg/weblate/issues/4379).
You can request new translations if you wish to translate.

**Comment by KazamaSion** [comment]
The language name "Dutch (Belgium)" is revised from "Finnish" now according to the official issue (https://github.com/WeblateOrg/weblate/issues/4379). It seems like the language list won't update automatically while upgrading the application, which needs a manual operation.
You can request new translations for "Dutch (Belgium)" in future if you wish to translate.

BTW, I found I misunderstand your issue in the first place, but your answer accidentally helps us solve an undiscovered issue. Thank you.

**Comment by liulex** [comment]
@Stephan-P Thanks for reporting. I think the untranslated Nederlands (without nl_NL) is gone now :)
